# -*- coding: utf-8 -*-
"""eda_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3AoQ0cE998MsKUWTax1XEhKi4px3o5O
"""

"""
Automated EDA Pre-processing Script
Author: [Your Name]
Purpose: Extract descriptive statistics and correlation matrices for LLM ingestion.
"""

import pandas as pd

def process_biometrics(file_path):
    # 1. Ingest Data
    print("Loading dataset...")
    df = pd.read_csv(file_path)

    # 2. Generate Descriptive Statistics
    desc_stats = df.describe().T

    # 3. Compute Correlation Matrix (dropping non-numeric ID)
    corr_matrix = df.drop(columns=['subject_id']).corr()

    # 4. Format for LLM Consumption
    analysis_df = pd.DataFrame({
        'Feature': desc_stats.index,
        'Mean': desc_stats['mean'].round(2),
        'Min': desc_stats['min'].round(2),
        'Max': desc_stats['max'].round(2),
        'Std_Dev': desc_stats['std'].round(2)
    })

    # 5. Export formatted CSV
    output_path = 'body_measurement_analysis.csv'
    analysis_df.to_csv(output_path, index=False)
    print(f"Data pre-processing complete. Ready for LLM ingestion. Exported to {output_path}")

if __name__ == "__main__":
    process_biometrics('body-messurement-data-set.csv')